name: Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: 'requirements*.txt'
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Install
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Lint
        run: flake8 custom_components/
      - name: Test
        run: pytest test/

      - name: Versioning
        run: |
          set +e # disable fail on exit code
          echo "PREVIOUS_TAG=$(cz version --project)" >> $GITHUB_ENV
          cz bump --changelog --changelog-to-stdout --yes > RELEASE_NOTES.md
          echo "RELEASE_TAG=$(cz version --project)" >> $GITHUB_ENV
          # only fail if exit code is not 0 or 21
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 21 ]; then
            exit "$EXIT_CODE"
          fi

      - name: Push and Release
        if: env.PREVIOUS_TAG != env.RELEASE_TAG
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
          git push origin --tags
          gh release create $RELEASE_TAG --notes-file RELEASE_NOTES.md --verify-tag
