name: Release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: 'requirements*.txt'
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Install
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Lint
        run: flake8 custom_components/
      - name: Test
        run: pytest test/

      - name: Versioning and Tags
        run: |
          cz bump --changelog --yes
          git push origin main
          git push origin --tags
          echo "RELEASE_TAG=$(cz --version)" >> $GITHUB_ENV
      - name: GitHub Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: 
            });
